name: Deploy Frontend Folder

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Pages
        uses: actions/configure-pages@v5

      # НОВЫЙ ШАГ: Подготовка артефакта
      # Мы копируем содержимое frontend в корень временной папки сборки
      - name: Подготовка файлов
        run: |
          mkdir _site
          cp -r frontend/* _site/

      - name: Загружаем файлы сайта
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем содержимое созданной папки _site
          path: '_site'

      - name: Публикация
        id: deployment
        uses: actions/deploy-pages@v4