name: Deploy Mini App to Pages

on:
  # Робот просыпается, когда мы делаем Push в ветку main
  push:
    branches: ["main"]

  # Позволяет запустить робота вручную кнопку с сайта
  workflow_dispatch:

# Права доступа для робота
permissions:
  contents: read
  pages: write
  id-token: write

# Только один робот может работать одновременно
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Задача: публикация
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Pages
        uses: actions/configure-pages@v5

      - name: Загружаем файлы из папки frontend
        uses: actions/upload-pages-artifact@v3
        with:
          # ВАЖНО: Укажи здесь имя своей папки с сайтом!
          path: './frontend'

      - name: Публикуем сайт
        id: deployment
        uses: actions/deploy-pages@v4